name: Metrics
on:
  # Schedule: runs at 4am every day
  schedule: [{cron: "0 4 * * *"}]
  # You can also run it manually
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          base_options: >
            timezone=Asia/Jakarta
