name: Metrics

on:
  # Jadwal: berjalan setiap jam 4 pagi
  schedule: [{cron: "0 4 * * *"}]
  # Anda juga bisa menjalankannya secara manual
  workflow_dispatch:

jobs:
  # Job 4: Untuk metrik klasik dengan plugin lines
  classic-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes
          
  # Job 1: Untuk menghasilkan kalender tahunan
  full-year-calendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
  
  # Job kedua: Untuk menampilkan bahasa dari repositori yang di-star
  starlists-languages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.starlists.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 8
          plugin_starlists_limit_repositories: 0
          
  # Job 3: Untuk menampilkan bahasa yang paling sering digunakan
  most-used-languages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.details.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4
