name: Metrics

on:
  # Jadwal: berjalan setiap jam 4 pagi
  schedule: [{cron: "0 4 * * *"}]
  # Anda juga bisa menjalankannya secara manual
  workflow_dispatch:

jobs:
  # Job pertama: Untuk menghasilkan kalender tahunan
  full-year-calendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
  
  # Job kedua: Untuk menghasilkan metrik lainnya
  other-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.repository.svg
          token: ${{ secrets.METRICS_TOKEN }}
          # Plugin seperti 'lines' dan 'projects' bekerja lebih baik dengan metrik dasar
          base: header, activity, community, repositories, metadata
          plugin_lines: yes
          plugin_followup: yes
          plugin_projects: yes
